-- CreateTable
CREATE TABLE `Halyava` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `looterId` INTEGER NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Halyava` ADD CONSTRAINT `Halyava_looterId_fkey` FOREIGN KEY (`looterId`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
